This is a workflow for tidying the hollar data and adding the relevant total_sesion action data associated
with the relevant day. Fortunately Hollar run their LOAD.SPOTS files consistently. 

With more complicated clients will need to do something more complicated

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [4]:
df = pd.read_csv('~/Dev/tvsquared-backend/tvsquared/tmp/cw/1337_current_all_data.csv')

dt_ts = pd.read_csv('~/Dev/tvsquared-backend/tvsquared/tmp/cw/client_1337_1_total_actions_per_day.csv')
dt_ts_sorted = dt_ts.sort_values(by="date")
print (dt_ts_sorted.dtypes)
dt_ts_sorted['date'] = pd.to_datetime(dt_ts_sorted['date'])
print (dt_ts_sorted.dtypes)
dt_ts_sorted

Unnamed: 0        int64
date             object
total_per_day     int64
dtype: object
Unnamed: 0                int64
date             datetime64[ns]
total_per_day             int64
dtype: object

    Unnamed: 0       date  total_per_day
32          32 2017-08-21          97615
5            5 2017-08-22          81086
46          46 2017-08-23          70373
4            4 2017-08-24          65179
36          36 2017-08-25          71353
25          25 2017-08-26          64605
0            0 2017-08-27          92115
18          18 2017-08-28          68162
44          44 2017-08-29          69001
37          37 2017-08-30          60359
13          13 2017-08-31          57438
28          28 2017-09-01          52466
49          49 2017-09-02          49014
7            7 2017-09-03          53006
30          30 2017-09-04          52508
40          40 2017-09-05          50013
11          11 2017-09-06          51820
21          21 2017-09-07          49104
35          35 2017-09-08          48048
3            3 2017-09-09          45560
16          16 2017-09-10          51796
39          39 2017-09-11          45869
43          43 2017-09-12          47037
17          17 2017-09-13          53045
27          27 2017-09-14          51690
47          47 2017-09-15         106802
12          12 2017-09-16          64537
23          23 2017-09-17         117787
42          42 2017-09-18          72632
1            1 2017-09-19          50000
24          24 2017-09-20          47119
34          34 2017-09-21          56357
2            2 2017-09-22          48989
14          14 2017-09-23          72388
29          29 2017-09-24          80581
48          48 2017-09-25          63379
8            8 2017-09-26          58924
33          33 2017-09-27          61167
41          41 2017-09-28          71883
9            9 2017-09-29          54680
22          22 2017-09-30          48844
26          26 2017-10-01          53448
31          31 2017-10-02          44521
6            6 2017-10-03          41176
38          38 2017-10-04          40279
15          15 2017-10-05          36405
19          19 2017-10-06          37891
45          45 2017-10-07          32869
20          20 2017-10-08          37075
10          10 2017-10-09          36020

In [12]:
df_trimmed =  df.drop(['Unnamed: 0','jobs', 'total_cost', 'total_time_in_queue', 
                         'total_time_under_calculation', 'total_time_waiting',
                         'total_time_waiting', 'total_time_under_calculation',
                         'total_cost','totalrowcount', 'spot_total', 
                         'spot_granularity_1', 
                         'workticket_scheduled', 'workticket_started', 'workticket_finished'], axis=1)
df_trimmed.head(15)

,brandid,clientid,cluster_info,diffuse,jobcount,jobpriority,lag,lag_actions,last_job,last_job_time,...,micro,modelrowcount,origin,rawsize,slug,spot_duration,spot_finish,spot_start,workticket_duration,workticketid
0,1,1337,{u'2': 1},True,42,1008.01,True,3,INF.SCRUBDB,8.467,...,True,123,US(1),236000000000,hollar,86400.0,2017-10-01 00:00:00.000,2017-10-01 00:00:00.000,28496.426,59d3a993b712c904285d161d
1,1,1337,{u'2': 1},True,43,1008.01,True,3,INF.SENDEMAIL,0.787,...,True,6140,US(1),236000000000,hollar,86400.0,2017-10-01 00:00:00.000,2017-10-01 00:00:00.000,16109.378,59d272f5b43fdd11cf3755e7
2,1,1337,{u'2': 1},True,41,1008.87,True,3,INF.SCRUBDB,4976.259,...,True,5709,US(1),236000000000,hollar,86400.0,2017-09-30 00:00:00.000,2017-09-30 00:00:00.000,35398.932,59d14245b43fdd0bb470d7d8
3,1,1337,{u'2': 1},True,41,1008.87,True,3,INF.SCRUBDB,4976.259,...,True,6808,US(1),236000000000,hollar,86400.0,2017-09-29 00:00:00.000,2017-09-29 00:00:00.000,35525.145,59d13d95b43fdd02d38811ba
4,1,1337,{u'2': 1},True,41,1008.87,True,3,INF.SCRUBDB,4.301,...,True,115,US(1),236000000000,hollar,86400.0,2017-09-29 00:00:00.000,2017-09-29 00:00:00.000,32855.169,59cfdc0c28c9cb560cc59eeb
5,1,1337,{u'2': 1},True,41,1008.87,True,3,INF.SCRUBDB,4.301,...,True,107,US(1),236000000000,hollar,86400.0,2017-09-28 00:00:00.000,2017-09-28 00:00:00.000,32877.989,59cfdbf328c9cb560cc59ee9
6,1,1337,{u'2': 1},True,42,1008.99,True,3,INF.SCRUBDB,4.077,...,True,4844,US(1),236000000000,hollar,86400.0,2017-09-13 00:00:00.000,2017-09-13 00:00:00.000,39356.100,59bab7f5b43fdd57c2ba341b
7,1,1337,{u'2': 1},True,43,1009.88,True,3,INF.SENDEMAIL,0.902,...,True,3902,US(1),236000000000,hollar,86400.0,2017-09-12 00:00:00.000,2017-09-12 00:00:00.000,67990.806,59b96673b43fdd4dc0032ed7
8,1,1337,{u'2': 1},True,44,1008.98,True,3,INF.SCRUBDB,3402.323,...,True,4764,US(1),236000000000,hollar,86400.0,2017-09-11 00:00:00.000,2017-09-11 00:00:00.000,44098.867,59b814f6b43fdd44596fb191
9,1,1337,{u'2': 1},True,44,1008.98,True,3,INF.SCRUBDB,3402.323,...,True,123,US(1),236000000000,hollar,86400.0,2017-09-10 00:00:00.000,2017-09-10 00:00:00.000,46364.730,59b80c14b712c92ef3c6ad7a
10,1,1337,{u'2': 1},True,43,1008.98,True,3,INF.SCRUBDB,5244.146,...,True,4860,US(1),236000000000,hollar,86400.0,2017-09-19 00:00:00.000,2017-09-19 00:00:00.000,46916.144,59c2a0f4b43fdd23562b50e4
11,1,1337,{u'2': 1},True,44,1008.01,True,3,INF.SENDEMAIL,0.807,...,True,109,US(1),236000000000,hollar,86400.0,2017-09-06 00:00:00.000,2017-09-06 00:00:00.000,32757.103,59b15dd33b34c922bac44205
12,1,1337,{u'2': 1},True,42,1008.01,True,3,INF.SCRUBDB,7712.427,...,True,4453,US(1),236000000000,hollar,86400.0,2017-09-14 00:00:00.000,2017-09-14 00:00:00.000,97835.631,59bc0976b43fdd57e1065d1a
13,1,1337,{u'2': 1},True,42,1008.98,True,3,INF.SCRUBDB,3.161,...,True,3708,US(1),236000000000,hollar,86400.0,2017-09-22 00:00:00.000,2017-09-22 00:00:00.000,24145.650,59c80314b43fdd0a35c630df
14,1,1337,{u'2': 1},True,42,1008.98,True,3,INF.SCRUBDB,4995.738,...,True,4942,US(1),236000000000,hollar,86400.0,2017-09-20 00:00:00.000,2017-09-20 00:00:00.000,37781.086,59c3f273b43fdd27c543c49c

In [6]:
cols = df_trimmed.columns.tolist()

new_cols = []
new_cols.insert(0, 'cluster_info')
new_cols.insert(0, 'jobcount')
new_cols.insert(0, 'workticketid')
new_cols.insert(0, 'lag')
new_cols.insert(0, 'origin')
new_cols.insert(0, 'last_job_time')
new_cols.insert(0, 'last_job')
new_cols.insert(0, 'workticket_duration')
new_cols.insert(0, 'spot_finish')
new_cols.insert(0, 'spot_start')
new_cols.insert(0, 'jobpriority')
new_cols.insert(0, 'lag_actions')
new_cols.insert(0, 'max_lag')
new_cols.insert(0, 'micro')
new_cols.insert(0, 'diffuse')
new_cols.insert(0, 'spot_duration')
new_cols.insert(0, 'modelrowcount')
new_cols.insert(0, 'rawsize')
new_cols.insert(0, 'slug')
new_cols.insert(0, 'clientid')
new_cols.insert(0, 'brandid')

df_trimmed = df_trimmed[new_cols]
df_trimmed.head()

,brandid,clientid,slug,rawsize,modelrowcount,spot_duration,diffuse,micro,max_lag,lag_actions,...,spot_start,spot_finish,workticket_duration,last_job,last_job_time,origin,lag,workticketid,jobcount,cluster_info
0,1,1337,hollar,236000000000,123,86400.0,True,True,14,3,...,2017-10-01 00:00:00.000,2017-10-01 00:00:00.000,28496.426,INF.SCRUBDB,8.467,US(1),True,59d3a993b712c904285d161d,42,{u'2': 1}
1,1,1337,hollar,236000000000,6140,86400.0,True,True,14,3,...,2017-10-01 00:00:00.000,2017-10-01 00:00:00.000,16109.378,INF.SENDEMAIL,0.787,US(1),True,59d272f5b43fdd11cf3755e7,43,{u'2': 1}
2,1,1337,hollar,236000000000,5709,86400.0,True,True,14,3,...,2017-09-30 00:00:00.000,2017-09-30 00:00:00.000,35398.932,INF.SCRUBDB,4976.259,US(1),True,59d14245b43fdd0bb470d7d8,41,{u'2': 1}
3,1,1337,hollar,236000000000,6808,86400.0,True,True,14,3,...,2017-09-29 00:00:00.000,2017-09-29 00:00:00.000,35525.145,INF.SCRUBDB,4976.259,US(1),True,59d13d95b43fdd02d38811ba,41,{u'2': 1}
4,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,2017-09-29 00:00:00.000,2017-09-29 00:00:00.000,32855.169,INF.SCRUBDB,4.301,US(1),True,59cfdc0c28c9cb560cc59eeb,41,{u'2': 1}

In [7]:
mask = df_trimmed['cluster_info'].str.contains('clone', na=False)
rem_clones = df_trimmed[mask == False]
rem_clones

rename = rem_clones.rename(columns={'modelrowcount': 'total_number_of_spots'})
rename.dropna(subset=['slug'], inplace=True)

rename

,brandid,clientid,slug,rawsize,total_number_of_spots,spot_duration,diffuse,micro,max_lag,lag_actions,...,spot_start,spot_finish,workticket_duration,last_job,last_job_time,origin,lag,workticketid,jobcount,cluster_info
0,1,1337,hollar,236000000000,123,86400.0,True,True,14,3,...,2017-10-01 00:00:00.000,2017-10-01 00:00:00.000,28496.426,INF.SCRUBDB,8.467,US(1),True,59d3a993b712c904285d161d,42,{u'2': 1}
1,1,1337,hollar,236000000000,6140,86400.0,True,True,14,3,...,2017-10-01 00:00:00.000,2017-10-01 00:00:00.000,16109.378,INF.SENDEMAIL,0.787,US(1),True,59d272f5b43fdd11cf3755e7,43,{u'2': 1}
2,1,1337,hollar,236000000000,5709,86400.0,True,True,14,3,...,2017-09-30 00:00:00.000,2017-09-30 00:00:00.000,35398.932,INF.SCRUBDB,4976.259,US(1),True,59d14245b43fdd0bb470d7d8,41,{u'2': 1}
3,1,1337,hollar,236000000000,6808,86400.0,True,True,14,3,...,2017-09-29 00:00:00.000,2017-09-29 00:00:00.000,35525.145,INF.SCRUBDB,4976.259,US(1),True,59d13d95b43fdd02d38811ba,41,{u'2': 1}
4,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,2017-09-29 00:00:00.000,2017-09-29 00:00:00.000,32855.169,INF.SCRUBDB,4.301,US(1),True,59cfdc0c28c9cb560cc59eeb,41,{u'2': 1}
5,1,1337,hollar,236000000000,107,86400.0,True,True,14,3,...,2017-09-28 00:00:00.000,2017-09-28 00:00:00.000,32877.989,INF.SCRUBDB,4.301,US(1),True,59cfdbf328c9cb560cc59ee9,41,{u'2': 1}
6,1,1337,hollar,236000000000,4844,86400.0,True,True,14,3,...,2017-09-13 00:00:00.000,2017-09-13 00:00:00.000,39356.100,INF.SCRUBDB,4.077,US(1),True,59bab7f5b43fdd57c2ba341b,42,{u'2': 1}
7,1,1337,hollar,236000000000,3902,86400.0,True,True,14,3,...,2017-09-12 00:00:00.000,2017-09-12 00:00:00.000,67990.806,INF.SENDEMAIL,0.902,US(1),True,59b96673b43fdd4dc0032ed7,43,{u'2': 1}
8,1,1337,hollar,236000000000,4764,86400.0,True,True,14,3,...,2017-09-11 00:00:00.000,2017-09-11 00:00:00.000,44098.867,INF.SCRUBDB,3402.323,US(1),True,59b814f6b43fdd44596fb191,44,{u'2': 1}
9,1,1337,hollar,236000000000,123,86400.0,True,True,14,3,...,2017-09-10 00:00:00.000,2017-09-10 00:00:00.000,46364.730,INF.SCRUBDB,3402.323,US(1),True,59b80c14b712c92ef3c6ad7a,44,{u'2': 1}
10,1,1337,hollar,236000000000,4860,86400.0,True,True,14,3,...,2017-09-19 00:00:00.000,2017-09-19 00:00:00.000,46916.144,INF.SCRUBDB,5244.146,US(1),True,59c2a0f4b43fdd23562b50e4,43,{u'2': 1}
11,1,1337,hollar,236000000000,109,86400.0,True,True,14,3,...,2017-09-06 00:00:00.000,2017-09-06 00:00:00.000,32757.103,INF.SENDEMAIL,0.807,US(1),True,59b15dd33b34c922bac44205,44,{u'2': 1}
12,1,1337,hollar,236000000000,4453,86400.0,True,True,14,3,...,2017-09-14 00:00:00.000,2017-09-14 00:00:00.000,97835.631,INF.SCRUBDB,7712.427,US(1),True,59bc0976b43fdd57e1065d1a,42,{u'2': 1}
13,1,1337,hollar,236000000000,3708,86400.0,True,True,14,3,...,2017-09-22 00:00:00.000,2017-09-22 00:00:00.000,24145.650,INF.SCRUBDB,3.161,US(1),True,59c80314b43fdd0a35c630df,42,{u'2': 1}
14,1,1337,hollar,236000000000,4942,86400.0,True,True,14,3,...,2017-09-20 00:00:00.000,2017-09-20 00:00:00.000,37781.086,INF.SCRUBDB,4995.738,US(1),True,59c3f273b43fdd27c543c49c,42,{u'2': 1}
15,1,1337,hollar,236000000000,124,86400.0,True,True,14,3,...,2017-09-11 00:00:00.000,2017-09-11 00:00:00.000,46347.665,INF.SCRUBDB,3402.323,US(1),True,59b80c2dc6d4312db328c4e4,44,{u'2': 1}
16,1,1337,hollar,236000000000,5579,86400.0,True,True,14,3,...,2017-09-07 00:00:00.000,2017-09-07 00:00:00.000,24949.409,INF.SCRUBDB,2311.234,US(1),True,59b2cef8b43fdd7ab725f9a3,42,{u'2': 1}
17,1,1337,hollar,236000000000,4880,86400.0,True,True,14,3,...,2017-09-08 00:00:00.000,2017-09-08 00:00:00.000,46507.145,INF.SCRUBDB,3402.323,US(1),True,59b80b8eb43fdd3691c632ab,44,{u'2': 1}
18,1,1337,hollar,236000000000,5183,86400.0,True,True,14,3,...,2017-08-31 00:00:00.000,2017-08-31 00:00:00.000,60955.424,INF.SCRUBDB,3475.738,US(1),True,59a99480b43fdd01dc871a07,49,NaN
19,1,1337,hollar,236000000000,128,86400.0,True,True,14,3,...,2017-09-12 00:00:00.000,2017-09-12 00:00:00.000,67901.359,INF.SENDEMAIL,0.811,US(1),True,59b99c259869ab4637ebbacb,43,{u'2': 1}
20,1,1337,hollar,236000000000,6606,86400.0,True,True,14,3,...,2017-09-06 00:00:00.000,2017-09-06 00:00:00.000,32751.798,INF.SENDEMAIL,0.819,US(1),True,59b17d74b43fdd4232abdece,43,{u'2': 1}
21,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,2017-09-08 00:00:00.000,2017-09-08 00:00:00.000,46439.455,INF.SCRUBDB,3402.323,US(1),True,59b80bd0c6d4312db328c4e2,44,{u'2': 1}
22,1,1337,hollar,236000000000,114,86400.0,True,True,14,3,...,2017-09-13 00:00:00.000,2017-09-13 00:00:00.000,41555.888,INF.SCRUBDB,4.077,US(1),True,59baacf5561f8342dce87d00,42,{u'2': 1}
23,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,2017-09-05 00:00:00.000,2017-09-05 00:00:00.000,32782.520,INF.SENDEMAIL,0.805,US(1),True,59b15db8c6d43120a74c6b94,44,{u'2': 1}
24,1,1337,hollar,236000000000,3791,86400.0,True,True,14,3,...,2017-09-15 00:00:00.000,2017-09-15 00:00:00.000,31296.591,INF.SCRUBDB,2012.452,US(1),True,59bec894b43fdd591704bbdc,42,{u'2': 1}
25,1,1337,hollar,236000000000,124,86400.0,True,True,14,3,...,2017-09-14 00:00:00.000,2017-09-14 00:00:00.000,99194.574,INF.SCRUBDB,7712.427,US(1),True,59bbe3363b34c905838d10d3,43,{u'2': 1}
26,1,1337,hollar,236000000000,120,86400.0,True,True,14,3,...,2017-09-09 00:00:00.000,2017-09-09 00:00:00.000,46394.824,INF.SCRUBDB,3402.323,US(1),True,59b80bfc3b34c92fb48d10a7,44,{u'2': 1}
27,1,1337,hollar,236000000000,4246,86400.0,True,True,14,3,...,2017-09-17 00:00:00.000,2017-09-17 00:00:00.000,20190.742,INF.SENDEMAIL,0.798,US(1),True,59bffdf1b43fdd3834355ad7,42,{u'2': 1}
28,1,1337,hollar,236000000000,117,86400.0,True,True,14,3,...,2017-09-25 00:00:00.000,2017-09-25 00:00:00.000,37903.022,INF.SCRUBDB,9.968,US(1),True,59cc1df85ad0b3054df6e62b,41,{u'2': 1}
29,1,1337,hollar,236000000000,4561,86400.0,True,True,14,3,...,2017-09-09 00:00:00.000,2017-09-09 00:00:00.000,25640.735,INF.SCRUBDB,3.360,US(1),True,59b6c81fb43fdd63b520bc01,42,{u'2': 1}
30,1,1337,hollar,236000000000,111,86400.0,True,True,14,3,...,2017-09-30 00:00:00.000,2017-09-30 00:00:00.000,28501.671,INF.SCRUBDB,8.467,US(1),True,59d3a9818a8845042edc6761,42,{u'2': 1}
31,1,1337,hollar,236000000000,4767,86400.0,True,True,14,3,...,2017-09-05 00:00:00.000,2017-09-05 00:00:00.000,16722.584,INF.SENDEMAIL,0.779,US(1),True,59b02bf6b43fdd449c9a47c7,43,{u'2': 1}
32,1,1337,hollar,236000000000,109,86400.0,True,True,14,3,...,2017-09-15 00:00:00.000,2017-09-15 00:00:00.000,31356.441,INF.SCRUBDB,2012.452,US(1),True,59be999bc6e39c7ef867a2f6,43,{u'2': 1}
33,1,1337,hollar,236000000000,3602,86400.0,True,True,14,3,...,2017-09-24 00:00:00.000,2017-09-24 00:00:00.000,15392.029,INF.SENDEMAIL,0.782,US(1),True,59c93874b43fdd352df809d8,42,{u'2': 1}
34,1,1337,hollar,236000000000,107,86400.0,True,True,14,3,...,2017-09-16 00:00:00.000,2017-09-16 00:00:00.000,31326.342,INF.SCRUBDB,2012.452,US(1),True,59be99bac6e39c7ef867a2f8,43,{u'2': 1}
35,1,1337,hollar,236000000000,3437,86400.0,True,True,14,3,...,2017-09-23 00:00:00.000,2017-09-23 00:00:00.000,24093.632,INF.SCRUBDB,3.161,US(1),True,59c807c1b43fdd1131bc8655,42,{u'2': 1}
36,1,1337,hollar,236000000000,4120,86400.0,True,True,14,3,...,2017-09-16 00:00:00.000,2017-09-16 00:00:00.000,31296.591,INF.SENDEMAIL,0.784,US(1),True,59becd44b43fdd601fd63965,42,{u'2': 1}
37,1,1337,hollar,236000000000,5372,86400.0,True,True,14,3,...,2017-09-18 00:00:00.000,2017-09-18 00:00:00.000,24344.460,INF.SENDEMAIL,0.835,US(1),True,59c1b8e8b43fdd32bc887208,43,{u'2': 1}
38,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,2017-09-04 00:00:00.000,2017-09-04 00:00:00.000,32812.622,INF.SENDEMAIL,0.796,US(1),True,59b15da23b34c922bbc4422e,44,{u'2': 1}
39,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,2017-09-17 00:00:00.000,2017-09-17 00:00:00.000,18477.788,INF.SENDEMAIL,1.860,US(1),True,59c16448561f8370ffe87c67,42,{u'2': 1}
40,1,1337,hollar,236000000000,4618,86400.0,True,True,14,3,...,2017-09-10 00:00:00.000,2017-09-10 00:00:00.000,26825.903,INF.SENDEMAIL,1.582,US(1),True,59b6c378b43fdd5ccbadac32,42,{u'2': 1}
41,1,1337,hollar,236000000000,4614,86400.0,True,True,14,3,...,2017-09-21 00:00:00.000,2017-09-21 00:00:00.000,28332.049,INF.SENDEMAIL,0.966,US(1),True,59c543f5b43fdd24a8215203,43,{u'2': 1}
42,1,1337,hollar,236000000000,105,86400.0,True,True,14,3,...,2017-08-31 00:00:00.000,2017-08-31 00:00:00.000,61474.414,INF.SCRUBDB,3475.738,US(1),True,59a99276702f070432a80404,49,NaN
43,1,1337,hollar,236000000000,7190,86400.0,True,True,14,3,...,2017-09-28 00:00:00.000,2017-09-28 00:00:00.000,21295.480,INF.SENDEMAIL,1.550,US(1),True,59ce7e76b43fdd40a047eff6,41,{u'2': 1}
44,1,1337,hollar,236000000000,9566,86400.0,True,True,14,3,...,2017-09-25 00:00:00.000,2017-09-25 00:00:00.000,44357.147,INF.SCRUBDB,4456.583,US(1),True,59ca89f3b43fdd6ccb9e7424,42,{u'2': 1}
45,1,1337,hollar,236000000000,117,86400.0,True,True,14,3,...,2017-09-25 00:00:00.000,2017-09-25 00:00:00.000,44281.522,INF.SCRUBDB,4456.583,US(1),True,59cade5a5ad0b3042965cfb7,41,{u'2': 1}
46,1,1337,hollar,236000000000,8466,86400.0,True,True,14,3,...,2017-09-26 00:00:00.000,2017-09-26 00:00:00.000,37962.726,INF.SCRUBDB,9.968,US(1),True,59cbdb77b43fdd10669a27f4,41,{u'2': 1}
47,1,1337,hollar,236000000000,111,86400.0,True,True,14,3,...,2017-09-26 00:00:00.000,2017-09-26 00:00:00.000,37903.022,INF.SCRUBDB,9.968,US(1),True,59cc1de55ad0b3054df6e629,41,{u'2': 1}
48,1,1337,hollar,236000000000,7103,86400.0,True,True,14,3,...,2017-09-27 00:00:00.000,2017-09-27 00:00:00.000,20680.404,INF.SENDEMAIL,0.799,US(1),True,59cd2cf7b43fdd574612dc02,41,{u'2': 1}
49,1,1337,hollar,236000000000,112,86400.0,True,True,14,3,...,2017-09-27 00:00:00.000,2017-09-27 00:00:00.000,20622.796,INF.SENDEMAIL,0.851,US(1),True,59cd383d2f4dd3058713599a,41,{u'2': 1}

In [8]:
temp = pd.DatetimeIndex(rename['spot_start'])
print (temp.dtype)
rename['spot_start_date'] = temp.date
rename['spot_start_time'] = temp.time
rename['spot_start_date'] = pd.to_datetime(rename['spot_start_date'])

print (rename.dtypes)

# rename['spot_start_time'], rename['spot_start_date'] = rename['spot_start_date'].apply(lambda x:x.time()), rename['spot_start_date'].apply(lambda x:x.date())

# df = pd.DataFrame({'Date':['2014-07-17 00:59:27.400189+00']})
# df['Date'] = pd.to_datetime(df['Date'])
# df['Time'],df['Date']= df['Date'].apply(lambda x:x.time()), df['Date'].apply(lambda x:x.date())
# df

datetime64[ns]
brandid                           int64
clientid                          int64
slug                             object
rawsize                           int64
total_number_of_spots             int64
spot_duration                   float64
diffuse                            bool
micro                              bool
max_lag                           int64
lag_actions                       int64
jobpriority                     float64
spot_start                       object
spot_finish                      object
workticket_duration             float64
last_job                         object
last_job_time                   float64
origin                           object
lag                                bool
workticketid                     object
jobcount                          int64
cluster_info                     object
spot_start_date          datetime64[ns]
spot_start_time                  object
dtype: object

In [9]:
rename_sorted = rename.sort_values(by="spot_start_date")
rename_sorted.drop(['spot_start'], axis=1)
rename_sorted.head(5)

,brandid,clientid,slug,rawsize,total_number_of_spots,spot_duration,diffuse,micro,max_lag,lag_actions,...,workticket_duration,last_job,last_job_time,origin,lag,workticketid,jobcount,cluster_info,spot_start_date,spot_start_time
42,1,1337,hollar,236000000000,105,86400.0,True,True,14,3,...,61474.414,INF.SCRUBDB,3475.738,US(1),True,59a99276702f070432a80404,49,NaN,2017-08-31,00:00:00
18,1,1337,hollar,236000000000,5183,86400.0,True,True,14,3,...,60955.424,INF.SCRUBDB,3475.738,US(1),True,59a99480b43fdd01dc871a07,49,NaN,2017-08-31,00:00:00
38,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,32812.622,INF.SENDEMAIL,0.796,US(1),True,59b15da23b34c922bbc4422e,44,{u'2': 1},2017-09-04,00:00:00
31,1,1337,hollar,236000000000,4767,86400.0,True,True,14,3,...,16722.584,INF.SENDEMAIL,0.779,US(1),True,59b02bf6b43fdd449c9a47c7,43,{u'2': 1},2017-09-05,00:00:00
23,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,32782.520,INF.SENDEMAIL,0.805,US(1),True,59b15db8c6d43120a74c6b94,44,{u'2': 1},2017-09-05,00:00:00

In [13]:
# merged = pd.merge(rename_sorted, data2, by="datetime")

# merged = pd.merge(rename_sorted, dt_ts_sorted, on='date', how='outer')

#merged = pd.merge_asof(rename_sorted, dt_ts_sorted, on='spot_start_date', by="total_per_day")
# print (rename_sorted.columns, rename_sorted.dtypes)
# print (dt_ts_sorted.columns, dt_ts_sorted.dtypes)
rename_sorted['date'] = rename_sorted['spot_start_date']
# dt_ts_sorted.columns


merged  = pd.merge(rename_sorted, dt_ts_sorted)
merged.head()

,brandid,clientid,slug,rawsize,total_number_of_spots,spot_duration,diffuse,micro,max_lag,lag_actions,...,origin,lag,workticketid,jobcount,cluster_info,spot_start_date,spot_start_time,date,Unnamed: 0,total_per_day
0,1,1337,hollar,236000000000,105,86400.0,True,True,14,3,...,US(1),True,59a99276702f070432a80404,49,NaN,2017-08-31,00:00:00,2017-08-31,13,57438
1,1,1337,hollar,236000000000,5183,86400.0,True,True,14,3,...,US(1),True,59a99480b43fdd01dc871a07,49,NaN,2017-08-31,00:00:00,2017-08-31,13,57438
2,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,US(1),True,59b15da23b34c922bbc4422e,44,{u'2': 1},2017-09-04,00:00:00,2017-09-04,30,52508
3,1,1337,hollar,236000000000,4767,86400.0,True,True,14,3,...,US(1),True,59b02bf6b43fdd449c9a47c7,43,{u'2': 1},2017-09-05,00:00:00,2017-09-05,40,50013
4,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,US(1),True,59b15db8c6d43120a74c6b94,44,{u'2': 1},2017-09-05,00:00:00,2017-09-05,40,50013

In [17]:
clean = merged
clean["total_session_actions"] = clean['total_per_day']
clean = merged.drop(['cluster_info','date', 'Unnamed: 0', 'spot_start_time', 'total_per_day'], axis=1)
clean.columns
clean

,brandid,clientid,slug,rawsize,total_number_of_spots,spot_duration,diffuse,micro,max_lag,lag_actions,...,spot_finish,workticket_duration,last_job,last_job_time,origin,lag,workticketid,jobcount,spot_start_date,total_session_actions
0,1,1337,hollar,236000000000,105,86400.0,True,True,14,3,...,2017-08-31 00:00:00.000,61474.414,INF.SCRUBDB,3475.738,US(1),True,59a99276702f070432a80404,49,2017-08-31,57438
1,1,1337,hollar,236000000000,5183,86400.0,True,True,14,3,...,2017-08-31 00:00:00.000,60955.424,INF.SCRUBDB,3475.738,US(1),True,59a99480b43fdd01dc871a07,49,2017-08-31,57438
2,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,2017-09-04 00:00:00.000,32812.622,INF.SENDEMAIL,0.796,US(1),True,59b15da23b34c922bbc4422e,44,2017-09-04,52508
3,1,1337,hollar,236000000000,4767,86400.0,True,True,14,3,...,2017-09-05 00:00:00.000,16722.584,INF.SENDEMAIL,0.779,US(1),True,59b02bf6b43fdd449c9a47c7,43,2017-09-05,50013
4,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,2017-09-05 00:00:00.000,32782.520,INF.SENDEMAIL,0.805,US(1),True,59b15db8c6d43120a74c6b94,44,2017-09-05,50013
5,1,1337,hollar,236000000000,109,86400.0,True,True,14,3,...,2017-09-06 00:00:00.000,32757.103,INF.SENDEMAIL,0.807,US(1),True,59b15dd33b34c922bac44205,44,2017-09-06,51820
6,1,1337,hollar,236000000000,6606,86400.0,True,True,14,3,...,2017-09-06 00:00:00.000,32751.798,INF.SENDEMAIL,0.819,US(1),True,59b17d74b43fdd4232abdece,43,2017-09-06,51820
7,1,1337,hollar,236000000000,5579,86400.0,True,True,14,3,...,2017-09-07 00:00:00.000,24949.409,INF.SCRUBDB,2311.234,US(1),True,59b2cef8b43fdd7ab725f9a3,42,2017-09-07,49104
8,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,2017-09-08 00:00:00.000,46439.455,INF.SCRUBDB,3402.323,US(1),True,59b80bd0c6d4312db328c4e2,44,2017-09-08,48048
9,1,1337,hollar,236000000000,4880,86400.0,True,True,14,3,...,2017-09-08 00:00:00.000,46507.145,INF.SCRUBDB,3402.323,US(1),True,59b80b8eb43fdd3691c632ab,44,2017-09-08,48048
10,1,1337,hollar,236000000000,4561,86400.0,True,True,14,3,...,2017-09-09 00:00:00.000,25640.735,INF.SCRUBDB,3.360,US(1),True,59b6c81fb43fdd63b520bc01,42,2017-09-09,45560
11,1,1337,hollar,236000000000,120,86400.0,True,True,14,3,...,2017-09-09 00:00:00.000,46394.824,INF.SCRUBDB,3402.323,US(1),True,59b80bfc3b34c92fb48d10a7,44,2017-09-09,45560
12,1,1337,hollar,236000000000,4618,86400.0,True,True,14,3,...,2017-09-10 00:00:00.000,26825.903,INF.SENDEMAIL,1.582,US(1),True,59b6c378b43fdd5ccbadac32,42,2017-09-10,51796
13,1,1337,hollar,236000000000,123,86400.0,True,True,14,3,...,2017-09-10 00:00:00.000,46364.730,INF.SCRUBDB,3402.323,US(1),True,59b80c14b712c92ef3c6ad7a,44,2017-09-10,51796
14,1,1337,hollar,236000000000,4764,86400.0,True,True,14,3,...,2017-09-11 00:00:00.000,44098.867,INF.SCRUBDB,3402.323,US(1),True,59b814f6b43fdd44596fb191,44,2017-09-11,45869
15,1,1337,hollar,236000000000,124,86400.0,True,True,14,3,...,2017-09-11 00:00:00.000,46347.665,INF.SCRUBDB,3402.323,US(1),True,59b80c2dc6d4312db328c4e4,44,2017-09-11,45869
16,1,1337,hollar,236000000000,128,86400.0,True,True,14,3,...,2017-09-12 00:00:00.000,67901.359,INF.SENDEMAIL,0.811,US(1),True,59b99c259869ab4637ebbacb,43,2017-09-12,47037
17,1,1337,hollar,236000000000,3902,86400.0,True,True,14,3,...,2017-09-12 00:00:00.000,67990.806,INF.SENDEMAIL,0.902,US(1),True,59b96673b43fdd4dc0032ed7,43,2017-09-12,47037
18,1,1337,hollar,236000000000,4844,86400.0,True,True,14,3,...,2017-09-13 00:00:00.000,39356.100,INF.SCRUBDB,4.077,US(1),True,59bab7f5b43fdd57c2ba341b,42,2017-09-13,53045
19,1,1337,hollar,236000000000,114,86400.0,True,True,14,3,...,2017-09-13 00:00:00.000,41555.888,INF.SCRUBDB,4.077,US(1),True,59baacf5561f8342dce87d00,42,2017-09-13,53045
20,1,1337,hollar,236000000000,4453,86400.0,True,True,14,3,...,2017-09-14 00:00:00.000,97835.631,INF.SCRUBDB,7712.427,US(1),True,59bc0976b43fdd57e1065d1a,42,2017-09-14,51690
21,1,1337,hollar,236000000000,124,86400.0,True,True,14,3,...,2017-09-14 00:00:00.000,99194.574,INF.SCRUBDB,7712.427,US(1),True,59bbe3363b34c905838d10d3,43,2017-09-14,51690
22,1,1337,hollar,236000000000,109,86400.0,True,True,14,3,...,2017-09-15 00:00:00.000,31356.441,INF.SCRUBDB,2012.452,US(1),True,59be999bc6e39c7ef867a2f6,43,2017-09-15,106802
23,1,1337,hollar,236000000000,3791,86400.0,True,True,14,3,...,2017-09-15 00:00:00.000,31296.591,INF.SCRUBDB,2012.452,US(1),True,59bec894b43fdd591704bbdc,42,2017-09-15,106802
24,1,1337,hollar,236000000000,107,86400.0,True,True,14,3,...,2017-09-16 00:00:00.000,31326.342,INF.SCRUBDB,2012.452,US(1),True,59be99bac6e39c7ef867a2f8,43,2017-09-16,64537
25,1,1337,hollar,236000000000,4120,86400.0,True,True,14,3,...,2017-09-16 00:00:00.000,31296.591,INF.SENDEMAIL,0.784,US(1),True,59becd44b43fdd601fd63965,42,2017-09-16,64537
26,1,1337,hollar,236000000000,4246,86400.0,True,True,14,3,...,2017-09-17 00:00:00.000,20190.742,INF.SENDEMAIL,0.798,US(1),True,59bffdf1b43fdd3834355ad7,42,2017-09-17,117787
27,1,1337,hollar,236000000000,119,86400.0,True,True,14,3,...,2017-09-17 00:00:00.000,18477.788,INF.SENDEMAIL,1.860,US(1),True,59c16448561f8370ffe87c67,42,2017-09-17,117787
28,1,1337,hollar,236000000000,5372,86400.0,True,True,14,3,...,2017-09-18 00:00:00.000,24344.460,INF.SENDEMAIL,0.835,US(1),True,59c1b8e8b43fdd32bc887208,43,2017-09-18,72632
29,1,1337,hollar,236000000000,4860,86400.0,True,True,14,3,...,2017-09-19 00:00:00.000,46916.144,INF.SCRUBDB,5244.146,US(1),True,59c2a0f4b43fdd23562b50e4,43,2017-09-19,50000
30,1,1337,hollar,236000000000,4942,86400.0,True,True,14,3,...,2017-09-20 00:00:00.000,37781.086,INF.SCRUBDB,4995.738,US(1),True,59c3f273b43fdd27c543c49c,42,2017-09-20,47119
31,1,1337,hollar,236000000000,4614,86400.0,True,True,14,3,...,2017-09-21 00:00:00.000,28332.049,INF.SENDEMAIL,0.966,US(1),True,59c543f5b43fdd24a8215203,43,2017-09-21,56357
32,1,1337,hollar,236000000000,3708,86400.0,True,True,14,3,...,2017-09-22 00:00:00.000,24145.650,INF.SCRUBDB,3.161,US(1),True,59c80314b43fdd0a35c630df,42,2017-09-22,48989
33,1,1337,hollar,236000000000,3437,86400.0,True,True,14,3,...,2017-09-23 00:00:00.000,24093.632,INF.SCRUBDB,3.161,US(1),True,59c807c1b43fdd1131bc8655,42,2017-09-23,72388
34,1,1337,hollar,236000000000,3602,86400.0,True,True,14,3,...,2017-09-24 00:00:00.000,15392.029,INF.SENDEMAIL,0.782,US(1),True,59c93874b43fdd352df809d8,42,2017-09-24,80581
35,1,1337,hollar,236000000000,117,86400.0,True,True,14,3,...,2017-09-25 00:00:00.000,37903.022,INF.SCRUBDB,9.968,US(1),True,59cc1df85ad0b3054df6e62b,41,2017-09-25,63379
36,1,1337,hollar,236000000000,9566,86400.0,True,True,14,3,...,2017-09-25 00:00:00.000,44357.147,INF.SCRUBDB,4456.583,US(1),True,59ca89f3b43fdd6ccb9e7424,42,2017-09-25,63379
37,1,1337,hollar,236000000000,117,86400.0,True,True,14,3,...,2017-09-25 00:00:00.000,44281.522,INF.SCRUBDB,4456.583,US(1),True,59cade5a5ad0b3042965cfb7,41,2017-09-25,63379
38,1,1337,hollar,236000000000,8466,86400.0,True,True,14,3,...,2017-09-26 00:00:00.000,37962.726,INF.SCRUBDB,9.968,US(1),True,59cbdb77b43fdd10669a27f4,41,2017-09-26,58924
39,1,1337,hollar,236000000000,111,86400.0,True,True,14,3,...,2017-09-26 00:00:00.000,37903.022,INF.SCRUBDB,9.968,US(1),True,59cc1de55ad0b3054df6e629,41,2017-09-26,58924
40,1,1337,hollar,236000000000,112,86400.0,True,True,14,3,...,2017-09-27 00:00:00.000,20622.796,INF.SENDEMAIL,0.851,US(1),True,59cd383d2f4dd3058713599a,41,2017-09-27,61167
41,1,1337,hollar,236000000000,7103,86400.0,True,True,14,3,...,2017-09-27 00:00:00.000,20680.404,INF.SENDEMAIL,0.799,US(1),True,59cd2cf7b43fdd574612dc02,41,2017-09-27,61167
42,1,1337,hollar,236000000000,107,86400.0,True,True,14,3,...,2017-09-28 00:00:00.000,32877.989,INF.SCRUBDB,4.301,US(1),True,59cfdbf328c9cb560cc59ee9,41,2017-09-28,71883
43,1,1337,hollar,236000000000,7190,86400.0,True,True,14,3,...,2017-09-28 00:00:00.000,21295.480,INF.SENDEMAIL,1.550,US(1),True,59ce7e76b43fdd40a047eff6,41,2017-09-28,71883
44,1,1337,hollar,236000000000,115,86400.0,True,True,14,3,...,2017-09-29 00:00:00.000,32855.169,INF.SCRUBDB,4.301,US(1),True,59cfdc0c28c9cb560cc59eeb,41,2017-09-29,54680
45,1,1337,hollar,236000000000,6808,86400.0,True,True,14,3,...,2017-09-29 00:00:00.000,35525.145,INF.SCRUBDB,4976.259,US(1),True,59d13d95b43fdd02d38811ba,41,2017-09-29,54680
46,1,1337,hollar,236000000000,5709,86400.0,True,True,14,3,...,2017-09-30 00:00:00.000,35398.932,INF.SCRUBDB,4976.259,US(1),True,59d14245b43fdd0bb470d7d8,41,2017-09-30,48844
47,1,1337,hollar,236000000000,111,86400.0,True,True,14,3,...,2017-09-30 00:00:00.000,28501.671,INF.SCRUBDB,8.467,US(1),True,59d3a9818a8845042edc6761,42,2017-09-30,48844
48,1,1337,hollar,236000000000,6140,86400.0,True,True,14,3,...,2017-10-01 00:00:00.000,16109.378,INF.SENDEMAIL,0.787,US(1),True,59d272f5b43fdd11cf3755e7,43,2017-10-01,53448
49,1,1337,hollar,236000000000,123,86400.0,True,True,14,3,...,2017-10-01 00:00:00.000,28496.426,INF.SCRUBDB,8.467,US(1),True,59d3a993b712c904285d161d,42,2017-10-01,53448

In [ ]:
clean.head()